import type { KnownIssue } from "./types";

export const ENGINE_ISSUES: KnownIssue[] = [
  {
    id: "engine-knock-detonation",
    title: "Engine knock / detonation (pinging)",
    category: "engine",
    description:
      "A metallic pinging or rattling under acceleration — like marbles in a can — usually means the fuel is igniting unevenly (detonation). Causes range from low-octane fuel and carbon buildup to faulty knock sensors or cooling issues.",
    sounds: ["knock", "rattle", "tick"],
    strongPhrases: ["accelerat", "under load", "uphill", "ping", "marbles"],
    supportingPhrases: ["fuel", "octane", "gas", "hot day", "spark"],
    contexts: { strong: ["acceleration"], weak: ["highway_speed"] },
    signals: { speed: "tracks_engine_rpm", load: "worse_under_load", locations: ["front"] },
    audioHints: ["rhythmic_ticking", "sharp_transients"],
    notFor: ["electric"],
    dampFor: ["diesel"],
    baseRate: 0.45,
    severity: "high",
    urgency: "prompt",
    safeToDrive: "caution",
    checksFirst: [
      "Try a tank of the octane grade the manufacturer recommends (or one step higher) and see if the noise fades.",
      "Check engine coolant temperature — running hot encourages knock.",
      "Note whether it only happens under load (accelerating, climbing) and disappears cruising.",
      "Note: diesels naturally clatter — for a diesel, compare against its normal sound.",
    ],
    confirmRuleOut: [
      "Knock that disappears with higher-octane fuel strongly suggests detonation.",
      "Knock at idle with no load is more worrying — that pattern points at mechanical wear (see rod knock).",
    ],
    repairDirection:
      "Start with fuel quality and a scan for knock-sensor codes; persistent detonation needs professional diagnosis before it damages pistons.",
    repairDifficulty: "pro",
    mechanicSummary:
      "Pinging under load. Please scan for codes, verify knock sensor operation, check for carbon buildup and cooling performance.",
  },
  {
    id: "rod-knock",
    title: "Rod knock (worn engine bearings)",
    category: "engine",
    description:
      "A deep, rhythmic knock from the bottom of the engine that speeds up with RPM — often worse when warm or under light load — can mean worn crankshaft rod bearings, usually from oil starvation. This is the most serious engine noise there is.",
    sounds: ["knock", "clunk", "rumble"],
    strongPhrases: ["deep knock", "bottom of the engine", "oil light", "oil pressure", "low oil", "rev"],
    supportingPhrases: ["warm", "louder with rpm", "idle", "rhythmic"],
    // Rod knock gets LOUDER warm and comes with oil-pressure trouble; the
    // opposite pattern argues strongly for lifter/manifold noise instead.
    negativePhrases: [
      "oil light never",
      "no oil light",
      "oil level is full",
      "oil is full",
      "only when cold",
      "goes away when warm",
      "gone once warm",
      "fades when warm",
    ],
    contexts: { strong: ["idle", "acceleration"], weak: ["cold_start"] },
    signals: { speed: "tracks_engine_rpm", temperature: "warm_only", locations: ["front"] },
    audioHints: ["rhythmic_ticking", "low_rumble", "loud_recording"],
    notFor: ["electric"],
    baseRate: 0.15,
    severity: "critical",
    urgency: "immediate",
    safeToDrive: "no",
    checksFirst: [
      "Check the oil level immediately — if it's low, top it up but don't assume that fixes the damage.",
      "Note whether the knock frequency rises directly with engine RPM.",
      "If the oil pressure light has flickered at all, stop driving now.",
    ],
    confirmRuleOut: [
      "A mechanic's stethoscope on the block and an oil-pressure test give a quick verdict.",
      "A lighter tick from the top of the engine that fades when warm is far more likely lifter noise (much less serious).",
    ],
    repairDirection:
      "Engine teardown: bearing replacement or engine rebuild/replacement. Continued driving typically destroys the engine — tow it if confirmed likely.",
    repairDifficulty: "pro-major",
    mechanicSummary:
      "Deep RPM-dependent knock, possible rod bearing. Please verify oil level/pressure and assess bottom end before any further driving.",
  },
  {
    id: "lifter-tick",
    title: "Lifter / valvetrain tick",
    category: "engine",
    description:
      "A light, fast ticking from the top of the engine — most noticeable at idle or right after a cold start, often fading as oil circulates — typically comes from hydraulic lifters or valvetrain clearances. Annoying, but usually not urgent.",
    sounds: ["tick", "click"],
    strongPhrases: ["tick", "top of the engine", "fades when warm", "cold start"],
    supportingPhrases: ["idle", "oil change", "fast ticking", "valve"],
    negativePhrases: ["louder when warm", "worse when warm", "louder as it warms"],
    contexts: { strong: ["idle", "cold_start"], weak: ["low_speed"] },
    signals: { speed: "tracks_engine_rpm", temperature: "cold_only", locations: ["front"] },
    audioHints: ["rhythmic_ticking", "high_pitched"],
    notFor: ["electric"],
    wear: { mileageFrom: 100_000 },
    baseRate: 0.55,
    severity: "low",
    urgency: "monitor",
    safeToDrive: "yes",
    checksFirst: [
      "Check the oil level and how overdue the oil change is — low or old oil is the most common cause.",
      "Note if the tick quiets down after the engine warms up for a few minutes.",
      "Confirm the tick speed is roughly half engine speed (valvetrain) rather than matching exhaust pulses.",
    ],
    confirmRuleOut: [
      "Fresh oil of the correct viscosity quieting the tick supports lifter noise.",
      "A tick that's loudest cold and disappears warm can also be a small exhaust manifold leak — have both checked together.",
    ],
    repairDirection:
      "Start with an oil change at correct viscosity; persistent loud ticking may need lifter or lash adjuster service.",
    repairDifficulty: "diy-easy",
    mechanicSummary:
      "Light valvetrain-style tick, prominent cold/idle. Please confirm oil condition and listen for lifter vs. exhaust manifold leak.",
  },
  {
    id: "vacuum-leak",
    title: "Vacuum leak",
    category: "engine",
    description:
      "A hissing from the engine bay at idle — often with a rough or unusually high idle — frequently means a cracked vacuum hose or leaking intake gasket letting unmetered air in.",
    sounds: ["hiss", "whine", "squeal"],
    strongPhrases: ["hiss", "rough idle", "high idle", "vacuum", "engine bay"],
    supportingPhrases: ["idle", "check engine", "stall", "hose"],
    contexts: { strong: ["idle"], weak: ["cold_start", "acceleration"] },
    signals: { locations: ["front"] },
    audioHints: ["broadband_hiss", "high_pitched"],
    notFor: ["electric"],
    dampFor: ["diesel"],
    wear: { ageFrom: 8 },
    baseRate: 0.5,
    severity: "moderate",
    urgency: "soon",
    safeToDrive: "yes",
    checksFirst: [
      "With the engine idling (transmission in park, parking brake on), listen around the intake area for a localized hiss.",
      "Look for cracked, brittle, or disconnected small rubber hoses.",
      "Check if the idle is rough, surging, or higher than normal, and whether the check-engine light is on (lean codes P0171/P0174 are typical).",
    ],
    confirmRuleOut: [
      "A shop smoke test finds vacuum leaks definitively.",
      "Hissing that continues after shutoff is more likely the cooling system venting — check coolant level instead.",
    ],
    repairDirection:
      "Replace the cracked hose or gasket — often a cheap fix once located.",
    repairDifficulty: "diy-moderate",
    mechanicSummary:
      "Idle hiss with possible lean running. Please smoke-test the intake for vacuum leaks and check for lean fuel-trim codes.",
  },
  {
    id: "turbo-bearing-whine",
    title: "Turbocharger bearing whine / whistle",
    category: "engine",
    description:
      "A healthy turbo whistles faintly under boost; a worn turbo bearing turns that into a loud rising whine or siren that tracks boost and RPM, sometimes with oil consumption or smoke on the overrun.",
    sounds: ["whine", "whistle", "hiss"],
    strongPhrases: ["turbo", "boost", "siren", "spool", "whistle under accel"],
    supportingPhrases: ["accelerat", "under load", "oil", "smoke"],
    contexts: { strong: ["acceleration"], weak: ["highway_speed"] },
    signals: { speed: "tracks_engine_rpm", load: "worse_under_load", locations: ["front"] },
    audioHints: ["tonal_whine", "high_pitched", "strong_harmonics"],
    notFor: ["electric"],
    wear: { mileageFrom: 90_000 },
    baseRate: 0.25,
    severity: "high",
    urgency: "prompt",
    safeToDrive: "caution",
    checksFirst: [
      "Notice whether the whistle/whine only appears under acceleration (boost) and fades when cruising.",
      "Check the oil level and look for blue-grey smoke on startup or when lifting off the throttle.",
      "Listen for a new 'siren' character — a healthy turbo is much subtler.",
    ],
    confirmRuleOut: [
      "A shop can check turbo shaft play at the compressor wheel in minutes.",
      "A whistle with no turbo on the car is an intake/vacuum leak instead — check which engine you have.",
    ],
    repairDirection:
      "Address early: a failing turbo bearing can shed its wheel and send debris through the engine. Rebuild or replace the turbo and fix its oil supply.",
    repairDifficulty: "pro-major",
    mechanicSummary:
      "Boost-dependent rising whine/siren, suspected turbo bearing. Please check shaft play, boost pressure, and oil feed.",
  },
  {
    id: "wastegate-flutter",
    title: "Wastegate / diverter flutter",
    category: "engine",
    description:
      "A fluttering or rapid 'wa-wa-wa' sound when you lift off the throttle after accelerating on a turbo car often comes from the wastegate or a diverter/blow-off valve venting — sometimes normal, sometimes a sticking valve.",
    sounds: ["flutter", "rattle"],
    strongPhrases: ["when i let off", "lift off after accelerating", "blow off", "wastegate", "flutter"],
    supportingPhrases: ["turbo", "boost", "accelerat"],
    contexts: { strong: ["acceleration"], weak: ["highway_speed"] },
    signals: { load: "worse_coasting", locations: ["front"] },
    audioHints: ["broadband_hiss"],
    notFor: ["electric"],
    baseRate: 0.2,
    severity: "low",
    urgency: "monitor",
    safeToDrive: "yes",
    checksFirst: [
      "Note that it happens specifically on throttle LIFT after boost, not during steady driving.",
      "Check for any loss of power or check-engine light alongside the sound.",
      "If the car is stock and drives normally, mild flutter is often just how the valve vents.",
    ],
    confirmRuleOut: [
      "Flutter only on lift-off after boost with normal power is usually benign valve behavior.",
      "Flutter WITH hesitation, limp mode, or a boost code points at a sticking wastegate/diverter that needs attention.",
    ],
    repairDirection:
      "If accompanied by power loss or codes, replace the diverter/wastegate actuator; otherwise document and monitor.",
    repairDifficulty: "pro",
    mechanicSummary:
      "Lift-off flutter after boost. Please verify diverter/wastegate operation and check for boost-related codes.",
  },
  {
    id: "boost-intake-leak",
    title: "Boost / intake (charge pipe) leak",
    category: "engine",
    description:
      "A split charge pipe or loose clamp on a turbo car hisses or whooshes loudly under acceleration and saps power, because pressurized intake air is escaping before the engine.",
    sounds: ["hiss", "whistle"],
    strongPhrases: ["hiss under accel", "whoosh when accelerating", "loses power when accelerating", "charge pipe", "intercooler pipe"],
    supportingPhrases: ["turbo", "boost", "check engine", "power"],
    negativePhrases: ["at idle only", "only at idle"],
    contexts: { strong: ["acceleration"], weak: [] },
    signals: { load: "worse_under_load", locations: ["front"] },
    audioHints: ["broadband_hiss"],
    notFor: ["electric"],
    baseRate: 0.25,
    severity: "moderate",
    urgency: "soon",
    safeToDrive: "yes",
    checksFirst: [
      "Notice the pairing: loud hiss under acceleration PLUS noticeably less power.",
      "Look for oily residue at intercooler pipe joints — leaks often spray fine oil mist.",
      "Check for a check-engine light (lean or underboost codes are typical).",
    ],
    confirmRuleOut: [
      "A boost-leak (pressure) test finds the split quickly and cheaply.",
      "A hiss at idle that disappears under load is more likely a vacuum leak.",
    ],
    repairDirection:
      "Reseat or replace the split hose/clamp — usually an inexpensive fix that restores the missing power immediately.",
    repairDifficulty: "diy-moderate",
    mechanicSummary:
      "Acceleration hiss with power loss, suspected charge-pipe leak. Please pressure-test the intake/boost plumbing.",
  },
  {
    id: "timing-chain-rattle",
    title: "Timing chain rattle (cold start)",
    category: "engine",
    description:
      "A stretched timing chain or weak tensioner rattles like a chain in a metal tube for the first seconds after a cold start, before oil pressure tightens things up. Common on many higher-mileage engines and worth catching early.",
    sounds: ["rattle", "tick"],
    strongPhrases: ["first few seconds", "few seconds on startup", "timing chain", "rattle on startup", "rattles when i start"],
    supportingPhrases: ["cold start", "morning", "oil", "start"],
    contexts: { strong: ["cold_start"], weak: ["idle"] },
    signals: { speed: "tracks_engine_rpm", temperature: "cold_only", locations: ["front"] },
    audioHints: ["rhythmic_ticking", "irregular_knocking"],
    notFor: ["electric"],
    wear: { mileageFrom: 100_000, ageFrom: 10 },
    baseRate: 0.35,
    severity: "high",
    urgency: "prompt",
    safeToDrive: "caution",
    checksFirst: [
      "Time it: chain rattle is loudest for the first 1\u20133 seconds after a cold start, then settles.",
      "Check oil level and viscosity — low or thin oil makes tensioners slow to pump up.",
      "Note whether the rattle is returning on warm restarts too (a worsening sign).",
    ],
    confirmRuleOut: [
      "Startup-only rattle that vanishes with oil pressure strongly suggests the chain/tensioner.",
      "A rattle that continues at all temperatures is more likely an exhaust shield or accessory.",
    ],
    repairDirection:
      "Replace the tensioner/guides (and chain if stretched) before a jumped chain turns it into engine damage.",
    repairDifficulty: "pro-major",
    mechanicSummary:
      "Cold-start chain rattle for the first seconds. Please check timing chain stretch and tensioner condition.",
  },
  {
    id: "vvt-phaser-rattle",
    title: "VVT / cam phaser rattle",
    category: "engine",
    description:
      "Variable valve timing phasers that lose oil pressure knock or rattle from the top front of the engine — classically at cold start or at low RPM under light load — and often set timing-related codes as they wear.",
    sounds: ["rattle", "knock", "tick"],
    strongPhrases: ["cam phaser", "vvt", "top of the engine rattle", "rattle at low rpm"],
    supportingPhrases: ["cold start", "oil", "check engine", "idle"],
    contexts: { strong: ["cold_start", "idle"], weak: ["acceleration"] },
    signals: { speed: "tracks_engine_rpm", locations: ["front"] },
    audioHints: ["rhythmic_ticking", "irregular_knocking"],
    notFor: ["electric"],
    wear: { mileageFrom: 90_000 },
    baseRate: 0.25,
    severity: "high",
    urgency: "prompt",
    safeToDrive: "caution",
    checksFirst: [
      "Check oil level and service history first — phasers are the first victims of neglected oil.",
      "Listen from the top front of the engine; phaser noise is higher up than a deep bottom-end knock.",
      "Watch for a check-engine light with camshaft timing codes.",
    ],
    confirmRuleOut: [
      "Timing codes plus a top-end rattle make a strong phaser case.",
      "A deep knock from low in the engine that worsens warm is the more serious rod-bearing pattern instead.",
    ],
    repairDirection:
      "Restore oil health first; worn phasers/solenoids need replacement before timing damage compounds.",
    repairDifficulty: "pro-major",
    mechanicSummary:
      "Top-end rattle with possible cam timing codes. Please check VVT phasers/solenoids and oil pressure.",
  },
  {
    id: "flexplate-crack",
    title: "Cracked flexplate / flywheel",
    category: "engine",
    description:
      "A cracked flexplate (the plate joining engine to automatic transmission) makes a hard metallic knock or clatter that is often loudest at idle in gear and can change or vanish at certain RPMs — easily mistaken for a rod knock.",
    sounds: ["knock", "clunk", "rattle"],
    strongPhrases: ["flexplate", "flywheel", "knock in gear at idle", "changes in park"],
    supportingPhrases: ["idle", "in gear", "starter", "bellhousing"],
    contexts: { strong: ["idle"], weak: ["acceleration", "cold_start"] },
    signals: { speed: "tracks_engine_rpm" },
    audioHints: ["rhythmic_ticking", "sharp_transients"],
    notFor: ["electric"],
    wear: { mileageFrom: 120_000 },
    baseRate: 0.12,
    severity: "high",
    urgency: "prompt",
    safeToDrive: "caution",
    checksFirst: [
      "Compare the knock in Drive (held on brake) versus Park/Neutral — a flexplate knock often changes distinctly.",
      "Note whether it appeared after recent transmission or starter work (bolts/alignment).",
      "Listen low at the bellhousing area rather than the top of the engine.",
    ],
    confirmRuleOut: [
      "A knock that changes with gear selection at the same RPM points away from rod bearings toward the flexplate.",
      "An oil-pressure warning or metal in the oil points back to the bottom end instead.",
    ],
    repairDirection:
      "Replace the flexplate — transmission-out labor, but far cheaper than the engine damage a wrong rod-knock diagnosis assumes.",
    repairDifficulty: "pro-major",
    mechanicSummary:
      "Metallic idle knock that changes between gear selections. Please inspect flexplate for cracks at the bellhousing.",
  },
  {
    id: "piston-slap",
    title: "Piston slap (cold)",
    category: "engine",
    description:
      "A hollow, muffled knocking on cold start that fades or disappears as the engine warms is often piston slap — extra piston-to-wall clearance when cold. Annoying, usually not urgent on engines known for it.",
    sounds: ["knock", "rattle"],
    strongPhrases: ["piston slap", "hollow knock", "knock when cold", "quiets when warm"],
    supportingPhrases: ["cold start", "morning", "fades", "warm"],
    negativePhrases: ["worse when warm", "louder when warm", "oil light"],
    contexts: { strong: ["cold_start"], weak: ["idle"] },
    signals: { speed: "tracks_engine_rpm", temperature: "cold_only", locations: ["front"] },
    audioHints: ["rhythmic_ticking", "low_rumble"],
    notFor: ["electric"],
    wear: { mileageFrom: 120_000, ageFrom: 12 },
    baseRate: 0.25,
    severity: "low",
    urgency: "monitor",
    safeToDrive: "yes",
    checksFirst: [
      "Confirm the pattern: knock on cold start that clearly fades within a few minutes of warming.",
      "Check that oil pressure is normal and the level is full.",
      "Compare against known behavior for your engine — some models slap for hundreds of thousands of miles.",
    ],
    confirmRuleOut: [
      "Cold-only knocking that fades warm with healthy oil pressure is the piston-slap pattern.",
      "A knock that stays or worsens when warm needs the serious rod-knock checks instead.",
    ],
    repairDirection:
      "Usually monitored, not repaired — fixing it properly means engine machining. Keep oil fresh and re-evaluate if it persists warm.",
    repairDifficulty: "pro-major",
    mechanicSummary:
      "Cold-start hollow knock fading warm, suspected piston slap. Please verify oil pressure and rule out rod bearing noise.",
  },
  {
    id: "injector-tick",
    title: "Fuel injector tick",
    category: "engine",
    description:
      "Modern injectors — especially direct-injection — tick audibly and rhythmically at idle in time with the engine. It is usually normal operating noise, just more noticeable on some cars and from outside the cabin.",
    sounds: ["tick", "click"],
    strongPhrases: ["injector", "ticking at idle", "direct injection"],
    supportingPhrases: ["idle", "engine bay", "rhythmic", "normal"],
    contexts: { strong: ["idle"], weak: ["cold_start"] },
    signals: { speed: "tracks_engine_rpm", locations: ["front"] },
    audioHints: ["rhythmic_ticking", "high_pitched"],
    notFor: ["electric"],
    dampFor: ["diesel"],
    baseRate: 0.45,
    severity: "low",
    urgency: "monitor",
    safeToDrive: "yes",
    checksFirst: [
      "Note that the tick is fast, even, and tracks engine speed exactly — that's the injection rhythm.",
      "Confirm the engine runs smoothly with no misfire or check-engine light.",
      "Compare loudness against a similar car if possible; DI engines tick by design.",
    ],
    confirmRuleOut: [
      "An even tick on a smooth-running engine with no codes is almost always normal injector noise.",
      "A tick that is louder when cold and fades warm may be the valvetrain or an exhaust leak instead — have both checked together.",
    ],
    repairDirection:
      "Usually no repair needed. If accompanied by rough running or codes, have the injectors tested.",
    repairDifficulty: "diy-easy",
    mechanicSummary:
      "Even RPM-synchronous tick at idle, likely normal injection noise. Please confirm no misfires or codes.",
  },
];
